repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: migrations-check
        language: system
        name: Check for uncreated migrations.
        entry: bash -c ".venv/bin/python3 manage.py makemigrations --check --dry-run"
        types: ["python"]
        pass_filenames: false
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: Sort imports
        args: [--profile=black]
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        name: Format files
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--ignore=E203,E501"]
        language_version: python3
