# Generated by Django 3.2.8 on 2021-10-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("implementations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="implementationcomment",
            name="upvotes",
        ),
    ]
