# Generated by Django 3.2.7 on 2021-09-13 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0004_auto_20210913_1858"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tags", "0002_alter_tag_name"),
        ("implementations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="implementation",
            old_name="user",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="implementation",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="implementation",
            name="completed_milestones",
            field=models.ManyToManyField(
                blank=True,
                related_name="completed_implementations",
                to="ideas.Milestone",
            ),
        ),
        migrations.AlterField(
            model_name="implementation",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="implementation",
            name="downvotes",
            field=models.ManyToManyField(
                blank=True,
                related_name="downvoted_implementations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="implementation",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="implementation_tags", to="tags.Tag"
            ),
        ),
        migrations.AlterField(
            model_name="implementation",
            name="upvotes",
            field=models.ManyToManyField(
                blank=True,
                related_name="upvoted_implementations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="implementation",
            name="views",
            field=models.ManyToManyField(
                blank=True,
                related_name="viewed_implementations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="implementationcomment",
            name="upvotes",
            field=models.ManyToManyField(
                blank=True,
                related_name="upvoted_implementation_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
