# Generated by Django 3.2.7 on 2021-09-28 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0004_auto_20210913_1858"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("implementations", "0002_auto_20210913_1858"),
    ]

    operations = [
        migrations.AddField(
            model_name="implementation",
            name="idea",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="implementations",
                to="ideas.idea",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="implementation",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="implementations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
