# Generated by Django 3.2.7 on 2021-09-30 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("implementations", "0003_auto_20210928_1642"),
    ]

    operations = [
        migrations.AlterField(
            model_name="implementationcomment",
            name="implementation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="implementations.implementation",
            ),
        ),
        migrations.AlterField(
            model_name="implementationcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="implementation_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
