# Generated by Django 3.2.7 on 2021-09-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("implementations", "0004_auto_20210930_1152"),
    ]

    operations = [
        migrations.RenameField(
            model_name="implementationcomment",
            old_name="user",
            new_name="owner",
        ),
        migrations.AddField(
            model_name="implementation",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="implementation",
            name="is_validated",
            field=models.BooleanField(default=False),
        ),
    ]
