# Generated by Django 3.2.7 on 2021-10-02 15:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("implementations", "0005_auto_20210930_1615"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="implementation",
            name="completed_milestones",
        ),
        migrations.AddField(
            model_name="implementation",
            name="completed_milestones",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(), default=list, size=10
            ),
        ),
    ]
