# Generated by Django 3.2.7 on 2021-10-03 14:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("implementations", "0007_alter_implementation_completed_milestones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="implementation",
            name="completed_milestones",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10),
                blank=True,
                default=list,
                size=20,
            ),
        ),
    ]
