# Generated by Django 3.2.8 on 2021-10-26 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("tags", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("ideas", "0001_initial"),
        ("implementations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bookmarked_ideas",
            field=models.ManyToManyField(
                blank=True, related_name="bookmarked_by", to="ideas.Idea"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bookmarked_implementations",
            field=models.ManyToManyField(
                blank=True,
                related_name="bookmarked_by",
                to="implementations.Implementation",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="favourite_tags",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="tags.Tag"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.Group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.Permission",
                verbose_name="user permissions",
            ),
        ),
    ]
