# Generated by Django 3.2.7 on 2021-09-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0001_initial"),
        ("implementations", "0001_initial"),
        ("accounts", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="saved_ideas",
            field=models.ManyToManyField(
                blank=True, related_name="user_saved_ideas", to="ideas.Idea"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="saved_implementations",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_saved_implementations",
                to="implementations.Implementation",
            ),
        ),
    ]
