# Generated by Django 3.2.7 on 2021-09-11 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20210910_1206"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="saved_implementations",
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="users_following", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
