# Generated by Django 3.2.7 on 2021-09-21 05:52

from django.db import migrations, models

import accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                blank=True,
                max_length=2048,
                null=True,
                validators=[accounts.validators.avatar_validator],
            ),
        ),
    ]
