# Generated by Django 3.2.7 on 2021-09-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0005_alter_idea_owner"),
        ("accounts", "0007_alter_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="saved_ideas",
        ),
        migrations.AddField(
            model_name="user",
            name="bookmarked_ideas",
            field=models.ManyToManyField(
                blank=True, related_name="bookmarked_by", to="ideas.Idea"
            ),
        ),
    ]
