# Generated by Django 3.2.7 on 2021-10-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("implementations", "0005_auto_20210930_1615"),
        ("accounts", "0009_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bookmarked_implementations",
            field=models.ManyToManyField(
                blank=True,
                related_name="bookmarked_by",
                to="implementations.Implementation",
            ),
        ),
    ]
