# Generated by Django 3.2.8 on 2021-10-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_user_bookmarked_implementations"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_email",
            field=models.BooleanField(default=False),
        ),
    ]
