# Generated by Django 3.2.8 on 2021-10-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_user_show_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordResetToken",
        ),
    ]
