# Generated by Django 3.2.7 on 2021-09-11 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ideas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="idea",
            old_name="user",
            new_name="owner",
        ),
        migrations.AlterField(
            model_name="idea",
            name="downvotes",
            field=models.ManyToManyField(
                blank=True, related_name="idea_downvotes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="idea",
            name="upvotes",
            field=models.ManyToManyField(
                blank=True, related_name="idea_upvotes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="idea",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="idea_views", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
