# Generated by Django 3.2.7 on 2021-09-13 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ideas", "0003_milestone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="body",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="idea",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="idea",
            name="downvotes",
            field=models.ManyToManyField(
                blank=True, related_name="downvoted_ideas", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="idea",
            name="upvotes",
            field=models.ManyToManyField(
                blank=True, related_name="upvoted_ideas", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="idea",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="viewed_ideas", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
