# Generated by Django 3.2.7 on 2021-10-02 15:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("implementations", "0006_auto_20211002_2105"),
        ("ideas", "0005_alter_idea_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="milestones",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=list, size=10
            ),
        ),
        migrations.DeleteModel(
            name="Milestone",
        ),
    ]
