# Generated by Django 3.2.7 on 2021-10-02 15:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0006_auto_20211002_2105"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="milestones",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=10,
            ),
        ),
    ]
