# Generated by Django 3.2.7 on 2021-10-03 11:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0007_alter_idea_milestones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="milestones",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=255), size=2
                ),
                blank=True,
                default=list,
                size=10,
            ),
        ),
    ]
