# Generated by Django 3.2.7 on 2021-09-05 12:55

from django.db import migrations, models

import tags.validators


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                error_messages={"unique": "This Tag already exists."},
                help_text="Tag name must be 1 to 50 characters long. \nIt may only contain lowercase alphabets, numbers and hyphens. \nIt shouldn't start or end with hyphens. \n It shouldn't contain consecutive hyphens",
                max_length=50,
                unique=True,
                validators=[tags.validators.TagNameValidator],
            ),
        ),
    ]
