# Generated by Django 3.2.7 on 2021-09-13 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discussions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="downvotes",
            field=models.ManyToManyField(
                blank=True,
                related_name="downvoted_discussions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="discussion",
            name="upvotes",
            field=models.ManyToManyField(
                blank=True,
                related_name="upvoted_discussions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="discussion",
            name="views",
            field=models.ManyToManyField(
                blank=True,
                related_name="viewed_discussions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="discussioncomment",
            name="upvotes",
            field=models.ManyToManyField(
                related_name="upvoted_discussion_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
