# Generated by Django 3.2.8 on 2021-10-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discussioncomment",
            name="upvotes",
        ),
    ]
