# Generated by Django 3.2.8 on 2021-10-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0003_auto_20211025_2204"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discussion",
            name="tags",
        ),
    ]
